/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Business.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo
 */
public class FormVehiculo extends javax.swing.JFrame {
Main m;
    /**
     * Creates new form FormVehiculo
     */
    public FormVehiculo(Main m) {
        this.m=m;
       
        initComponents();
         this.cargarPropietario();
    }

    
    public FormVehiculo() {
        initComponents();
    }
    
    private void cargarPropietario(){
        String [] cadena=this.m.listarPropietario().split("-");
       
        for(int i=0;i<cadena.length;i++){
           this.cmbPropietario.addItem(cadena[i]);
        }
    }
    
    private void limpliar(){
        this.txtPlaca.setText("");
        this.txtMarca.setText("");
        this.txtModelo.setText("");
        this.cmbPropietario.setSelectedIndex(0);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btModificar = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        btRegistrarPropietario = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        cmbPropietario = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 175, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dueño:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 215, -1, -1));

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 270, -1, -1));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 225, -1));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 225, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 225, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 95, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 135, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrar Vehiculos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 25, -1, -1));

        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 270, -1, -1));

        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 270, -1, -1));

        btRegistrarPropietario.setText("+");
        btRegistrarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarPropietarioActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrarPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 212, 24, -1));

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 270, -1, -1));

        cmbPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPropietarioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 212, 225, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        
        FormMain f=new FormMain(this.m);
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btSalirActionPerformed

    private void btRegistrarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarPropietarioActionPerformed
        // TODO add your handling code here:
        
        FormPropietario f=new FormPropietario(this.m);
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btRegistrarPropietarioActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        // TODO add your handling code here:
        
        String placa=this.txtPlaca.getText();
        String marca=this.txtMarca.getText();
        String modelo=this.txtModelo.getText();
        String [] propietario=((String) this.cmbPropietario.getSelectedItem()).split(" ");
        
        if("".equals(placa)||"".equals(marca)||"".equals(modelo)){
             JOptionPane.showMessageDialog(null, "Faltan datos por ingresar");
        }else{
           String res= this.m.guardarVehiculo(placa, modelo, marca, propietario[0]);
           JOptionPane.showMessageDialog(null, res);
           this.limpliar();
        }
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void cmbPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPropietarioActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        String placa=this.txtPlaca.getText();
        if("".equals(placa)){
           JOptionPane.showMessageDialog(null, "Ingrese la placa del vehiculo"); 
        }else{
            String [] res=this.m.consultarVehiculo(placa).split("-");
            if("Vehiculo no existe".equals(res[0])){
                 JOptionPane.showMessageDialog(null, res[0]); 
            }else{
                this.txtModelo.setText(res[1]);
                this.txtMarca.setText(res[2]);
                
                for(int i=0;i<this.cmbPropietario.getItemCount();i++){
                    String [] seleccion=this.cmbPropietario.getItemAt(i).split(" ");
                    if(seleccion[0].equals(res[3])){
                        this.cmbPropietario.setSelectedIndex(i);
                    }
                }
               
            }
        }
        
        
        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        
        String placa=this.txtPlaca.getText();
        String marca=this.txtMarca.getText();
        String modelo=this.txtModelo.getText();
        String [] propietario=((String) this.cmbPropietario.getSelectedItem()).split(" ");
        
        if("".equals(placa)||"".equals(marca)||"".equals(modelo)){
             JOptionPane.showMessageDialog(null, "Faltan datos por ingresar");
        }else{
           String res= this.m.modificarVehiculo(placa, modelo, marca, propietario[0]);
           JOptionPane.showMessageDialog(null, res);
           this.limpliar();
        }

    }//GEN-LAST:event_btModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FormVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btRegistrarPropietario;
    private javax.swing.JButton btSalir;
    private javax.swing.JComboBox<String> cmbPropietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
